apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadvqic4794-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadvqic4794-tenant-component
    app.kubernetes.io/part-of: loadvqic4794-tenant-app
  name: loadvqic4794-tenant-component
  namespace: loadvqic4794-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadvqic4794-tenant-component
    weight: null
status: {}
